/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ventanas;
import com.mycompany.proyecto1buses.Cliente;
import com.mycompany.proyecto1buses.data;
import com.mycompany.proyecto1buses.Boleto;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author matia
 */
public class AnularBoleto extends javax.swing.JFrame {
    
    private data db;
    private Cliente cliente;

    /**
     * Creates new form AnularBoleto
     */
    public AnularBoleto(data db,Cliente cliente) {
        this.setLocationRelativeTo(null);
        this.db = db;
        this.cliente = cliente;
        initComponents();
        llenarJCombo();
    }
    
    public void llenarJCombo(){
        for (Boleto boleto : cliente.getBoletosEnPosesion()) {
            CiudadJCombo.addItem(boleto.getCiudadDestino());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        reembolsarButton = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CiudadJCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Que boleto desea anular?");

        reembolsarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reembolsarButton.setText("REEMBOLSAR");

        Volver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Volver.setText("VOLVER");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Terminal destino:");

        CiudadJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadJComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reembolsarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(CiudadJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CiudadJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver)
                    .addComponent(reembolsarButton))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CiudadJComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudadJComboActionPerformed
        // TODO add your handling code here:
        reembolsarButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
        String terminalSeleccionado = (String) CiudadJCombo.getSelectedItem();
        int indiceBoletoSeleccionado = -1;

        // Buscar el índice del boleto seleccionado
        for (int i = 0; i < cliente.getBoletosEnPosesion().size(); i++) {
            Boleto boleto = cliente.getBoletosEnPosesion().get(i);
            if (boleto.getTerminalDestino().equals(terminalSeleccionado)) {
                indiceBoletoSeleccionado = i;
                break;  // Detener el bucle después de encontrar el primer boleto que coincide
            }
        }

        if (indiceBoletoSeleccionado != -1) {
            Boleto boletoSeleccionado = cliente.getBoletosEnPosesion().get(indiceBoletoSeleccionado);

            // Mostrar el mensaje de reembolso
            JOptionPane.showMessageDialog(null, "El boleto al terminal " + terminalSeleccionado + " ha sido anulado con éxito. Se te ha reembolsado $" + boletoSeleccionado.getValorBoleto());

            // Eliminar el boleto de la lista de boletos del cliente
            cliente.getBoletosEnPosesion().remove(indiceBoletoSeleccionado);

            // Actualizar el JComboBox
            CiudadJCombo.removeItem(terminalSeleccionado);
        }
    }
});





    }//GEN-LAST:event_CiudadJComboActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        MenuCliente menu = new MenuCliente(db,cliente);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CiudadJCombo;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton reembolsarButton;
    // End of variables declaration//GEN-END:variables
}
