/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ventanas;
import com.mycompany.proyecto1buses.Cliente;
import com.mycompany.proyecto1buses.data;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

/**
 *
 * @author matia
 */
public class MenuCliente extends javax.swing.JFrame {
    String currentFolder = Paths.get("").toAbsolutePath().toString();
      
      //directorios para las peliculas
      String txtCiudades = currentFolder + "/src/main/java/com/mycompany/data/ciudades.txt";
      String csvClientes = currentFolder + "/src/main/java/com/mycompany/data/clientes.csv";
    
    private  data db;
    private  Cliente cliente;

    /**
     * Creates new form MenuCliente
     */
    public MenuCliente(data db, Cliente cliente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.db = db;
        this.cliente = cliente;
        welcomeLabel();
    }
    
    private void welcomeLabel(){
        
        jLabel2.setText("Bienvenido "+cliente.getNombreUsuario());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comprarBoleto = new javax.swing.JButton();
        verBoletos = new javax.swing.JButton();
        anularBoleto = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("¿Que desea hacer?");

        comprarBoleto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comprarBoleto.setText("Comprar Boleto");
        comprarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBoletoActionPerformed(evt);
            }
        });

        verBoletos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verBoletos.setText("Ver mis Boletos");
        verBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBoletosActionPerformed(evt);
            }
        });

        anularBoleto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        anularBoleto.setText("Anular Boleto");

        cerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comprarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(verBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anularBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comprarBoleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verBoletos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anularBoleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cerrarSesion)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBoletoActionPerformed
        // TODO add your handling code here:
        Comprar compra = new Comprar(db,cliente);
        compra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_comprarBoletoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:    
        int i = JOptionPane.showConfirmDialog(this, "Seguro que quieres salir?"); 
        if (i == 0)
        {
            db.exportarClientes(csvClientes);
            portada port = new portada(db,cliente);
            port.setVisible(true);
            this.dispose();
        }        

    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void verBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBoletosActionPerformed
        // TODO add your handling code here:
        VerBoletos ver = new VerBoletos(db,cliente);
        ver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verBoletosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anularBoleto;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton comprarBoleto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton verBoletos;
    // End of variables declaration//GEN-END:variables
}
